### ISSUE TITLE
Installation failure on windows 10

### ISSUE THREAD

**Issue by sebastianloesch** [PersoSim/de.persosim.driver.win#5]
Installation fails with

0x80070643 - Schwerwiegender Fehler bei der Installation.

Log file is attached

**Comment by sebastianloesch** [comment]
[log.txt](https://github.com/PersoSim/de.persosim.driver.win/files/4785655/log.txt)

**Comment by hfunke** [comment]
This failure and the corresponding workaround is documented in our FAQ already: https://persosim.secunet.com/de/faq/

**Comment by sebastianloesch** [comment]
Thank you for the quick response. That fixed the problem.
